In [4]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from PIL import Image
from numpy import asarray
from sklearn.model_selection import train_test_split
!pip install rawpy
import rawpy
from os.path import dirname, join as pjoin
import scipy.io as sio

In [5]:
# X_train numpy array (536,400)
matstruct_fname = 'input.mat'
arr = sio.loadmat(matstruct_fname, struct_as_record = False)
#print(arr)
print(arr['m'])
finalNA = arr['m']
finalNA.shape
#print(type(finalNA))
fin = np.array([],[])
fin.shape
data1 = im.fromarray(finalNA)
data1.save('first.png')

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 5 5 5]
 [0 0 0 ... 5 5 5]
 [0 0 0 ... 5 5 5]]


In [6]:
#get distance from mean
def distance(p1, mean):
    dist = abs(p1-mean)
    return dist

In [7]:
hell = [[1,1],[2,2],[3,3]]
for r in range(3):
    for c in range(2):
        print([r,c])

[0, 0]
[0, 1]
[1, 0]
[1, 1]
[2, 0]
[2, 1]


In [8]:
def KNN():
    #indexM = [[0,0],[0,0],[0,0], [0,0]]
    mean = [0,85,170,255]
    
    for i in range(2):
        values = [[0],[0],[0],[0]]
        valr = [[0],[0],[0],[0]]
        valc = [[0],[0],[0],[0]]
        print(len(values[0]))
        for r in range(len(finalNA)):
            for c in range(len(finalNA[0])): 
                
                min1 = distance(finalNA[r][c], mean[0])
                temp = 0
                
                for x in range(1,4):
                    dis = distance(finalNA[r][c], mean[x])
                    if(min1 > dis):
                        min1 = dis
                        temp = x
                values[temp].append(finalNA[r][c])
                valr[temp].append(r)
                valc[temp].append(c)
                #indexM[temp].append([r,c])
                
        for j in range(len(values)):
            add = 0
            for f in range(1, len(values[j])):
                add = add + values[j][f]
            mean[j] = add/len(values[j])
        print(mean)
    tot8=0
    #finalNA.astype(np.float)
    for a in range(len(values)):
        print(a)
        print(len(values[a]))
        for b in range(1,len(values[a])):
            finalNA[valr[a][b], valc[a][b]] = mean[a]
            if(finalNA[valr[a][b], valc[a][b]] == 162): tot8 = tot8+1
    print(tot8)    
    arr = finalNA.astype('float64')
    return arr

In [9]:
KNN()

1
[8.248721884665947, 76.2633398424726, 167.44397721625444, 249.3481323396068]
1
[8.248721884665947, 74.1315648262876, 162.27483437665396, 248.48346325588435]
0
390223
1
102497
2
54793
3
92491
54792


array([[8., 8., 8., ..., 8., 8., 8.],
       [8., 8., 8., ..., 8., 8., 8.],
       [8., 8., 8., ..., 8., 8., 8.],
       ...,
       [8., 8., 8., ..., 8., 8., 8.],
       [8., 8., 8., ..., 8., 8., 8.],
       [8., 8., 8., ..., 8., 8., 8.]])

In [10]:
from PIL import Image as im
data = im.fromarray(finalNA)
data.save('output.png')